version: "3.8"

services:
 traefik:
  image: traefik:2.9.10
  env_file:
   - ./conf.env
  container_name: traefik
  restart: unless-stopped
  networks:
   - traefik
  ports:
   - 80:80
   - 443:443
  volumes:
   - ./traefik.yaml:/traefik.yaml:ro
   - ./data/acme.json:/acme.json:rw # touch amce.json && sudo chmod 600 acme.json
   - ./configs:/configs:ro
   - /var/run/docker.sock:/var/run/docker.sock:ro
  labels:
   - traefik.enable=true
   - traefik.http.routers.dashboard.entrypoints=https
   - traefik.http.routers.dashboard.rule=Host(`traefik.boket78.com`)
   - traefik.http.routers.dashboard.service=api@internal
   - traefik.http.routers.dashboard.tls.certresolver=dns
networks: # I'd recommend creating a dedicated docker network via docker network create <name> honestly..
  traefik: