api:
    dashboard: true
    insecure: false # So we can define the api@internal over it just being on 8080. 

ping: # If you are using traefik behind proxied cloudflare we'll send certain updates to cloudflare when traefik is restarting or being shut down
  manualRouting: true 
  terminatingStatusCode: 503

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: true
  https:
    address: ":443"
    http:
      tls:
         options: default
         certresolver: dns

providers:
 docker:
  exposedByDefault: false
  swarmMode: false
  defaultRule: "Host(`{{ index .Labels \"com.docker.compose.service\"}}.boket78.com`)"
  network: traefik
 file:
  directory: '/configs'
  watch: true

certificatesResolvers:
  dns:
    acme:
      email: mislavperic32@gmail.com
      storage: acme.json
      dnsChallenge:
        provider: porkbun
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
log:
  level: info